## Importing the data

In [85]:
import pandas as pd
insp = pd.read_csv("inspections.csv")
network = pd.read_csv("network.csv")
samplesub = pd.read_csv("sample_submission.csv")

In [86]:
samplesub

           PipeId  Incidence
0       446859944          0
1       428124500          0
2       438428871          0
3       429034569          0
4       411184477          0
...           ...        ...
909728  235426649          0
909729  235426673          0
909730  235426707          0
909731  190956601          0
909732  228228379          0

[909733 rows x 2 columns]

In [87]:
network

,PipeId,Province,Town,YearBuilt,Material,GasType,Diameter,Length,Pressure,NumConnections,NumConnectionsUnder,BoolBridle
0,489616,Ciudad Real,Torralba de Calatrava,2012,PE,Gas natural,63.0,7.792,0.4,0,0,False
1,489645,Ciudad Real,Torralba de Calatrava,2012,PE,Gas natural,90.0,2.080,0.4,0,0,False
2,489646,Ciudad Real,Torralba de Calatrava,2012,PE,Gas natural,90.0,111.173,0.4,3,0,False
3,519950,Ciudad Real,Torralba de Calatrava,2012,PE,Gas natural,200.0,14.304,0.4,0,0,False
4,1332439,Ciudad Real,Torralba de Calatrava,2012,PE,Gas natural,160.0,22.669,0.4,1,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1446534,416536087,La Rioja,Baños de Rio Tobia,2011,AO,Gas natural,50.8,0.454,45.0,0,0,False
1446535,416536416,La Rioja,Baños de Rio Tobia,2011,AO,Gas natural,101.6,0.478,45.0,0,0,False
1446536,416536438,La Rioja,Baños de Rio Tobia,2011,AO,Gas natural,101.6,0.485,45.0,0,0,False
1446537,416536460,La Rioja,Baños de Rio Tobia,2011,AO,Gas natural,50.8,0.210,45.0,0,0,False
1446538,416536482,La Rioja,Baños de Rio Tobia,2011,AO,Gas natural,50.8,0.795,45.0,0,0,False

## Merging the datasets

In [88]:
data = insp.merge(network, how='inner', on='PipeId')

data = data.drop(columns=['MaintenanceId', 'InspectionDate', 'Town'])

df = pd.get_dummies(data['Province'])

# join the encoded dataframe with original dataframe
data = data.join(df)

df1 = pd.get_dummies(data['GasType'])

# join the encoded dataframe with original dataframe
data = data.join(df1)

df2 = pd.get_dummies(data['BoolBridle'])

# join the encoded dataframe with original dataframe
data = data.join(df2)

df3 = pd.get_dummies(data['Material'])

# join the encoded dataframe with original dataframe
data = data.join(df3)

data = data.drop(columns=['GasType', 'BoolBridle', 'Material',"Province"])

data.drop_duplicates(subset=["PipeId"], keep = "last", inplace = True)

data

,PipeId,InspectionYear,MonthsLastRev,Severity,Incidence,YearBuilt,Diameter,Length,Pressure,NumConnections,...,CU,FD,FG,FI,FO,PA,PE,PN,PV,ZD
5,189311802,2020,24,4,0,2001,160.0,117.831,4.000,0,...,0,0,0,0,0,0,1,0,0,0
11,188889914,2019,24,4,0,1999,160.0,1.292,0.025,0,...,0,0,0,0,0,0,1,0,0,0
17,188889907,2019,24,4,0,1992,200.0,28.193,0.025,1,...,0,0,0,0,0,0,1,0,0,0
23,188673355,2019,24,4,0,1998,200.0,66.259,0.025,5,...,0,0,0,0,0,0,1,0,0,0
29,188558922,2019,24,4,0,1999,160.0,0.810,0.025,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6345339,56922448,2020,24,4,0,1993,63.0,1.237,4.000,0,...,0,0,0,0,0,0,1,0,0,0
6345340,56907425,2020,24,4,0,2000,160.0,169.732,4.000,1,...,0,0,0,0,0,0,1,0,0,0
6345341,7843615,2021,24,4,0,1995,150.0,0.361,0.025,0,...,0,1,0,0,0,0,0,0,0,0
6345342,56922456,2020,24,4,0,1993,63.0,23.306,4.000,0,...,0,0,0,0,0,0,1,0,0,0
6345343,56922465,2020,24,4,0,1993,63.0,1.778,4.000,0,...,0,0,0,0,0,0,1,0,0,0

In [89]:
finalsub = samplesub.merge(data, how='left', on='PipeId')
finalsub = finalsub.drop("Incidence_x", axis = 1)
finalsub

,PipeId,InspectionYear,MonthsLastRev,Severity,Incidence_y,YearBuilt,Diameter,Length,Pressure,NumConnections,...,CU,FD,FG,FI,FO,PA,PE,PN,PV,ZD
0,446859944,2019.0,23.0,4.0,0.0,2012.0,110.0,44.286,0.150,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,428124500,2019.0,24.0,4.0,0.0,2012.0,160.0,110.715,0.150,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,438428871,2019.0,23.0,4.0,0.0,2012.0,110.0,13.575,0.150,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,429034569,2019.0,23.0,4.0,0.0,2012.0,110.0,327.689,0.150,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,411184477,2019.0,23.0,4.0,0.0,2007.0,200.0,932.762,0.150,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909728,235426649,2020.0,24.0,4.0,0.0,2004.0,110.0,7.656,0.025,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909729,235426673,2020.0,24.0,4.0,0.0,2004.0,110.0,4.383,0.025,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909730,235426707,2020.0,24.0,4.0,0.0,2004.0,110.0,2.292,0.025,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909731,190956601,2020.0,24.0,4.0,0.0,2004.0,90.0,87.809,4.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909732,228228379,2020.0,24.0,4.0,0.0,2004.0,160.0,2.325,4.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

## EDA

Counting the number of 0 and 1 and the rate

## Modeling

### Making the ss

In [93]:
df = data
df = df.sample(frac=1)
incidence_df = df.loc[df['Incidence'] == 1]
non_incidence_df = df.loc[df['Incidence'] == 0][:100000]
normal_distributed_df = pd.concat([incidence_df, non_incidence_df])
new_df = normal_distributed_df.sample(frac=1, random_state=42)
new_df.sample(3)

,PipeId,InspectionYear,MonthsLastRev,Severity,Incidence,YearBuilt,Diameter,Length,Pressure,NumConnections,...,CU,FD,FG,FI,FO,PA,PE,PN,PV,ZD
3154394,190693252,2019,25,4,0,2000,110.0,27.722,0.15,1,...,0,0,0,0,0,0,1,0,0,0
4670372,428126020,2019,25,4,0,2012,160.0,29.789,0.15,0,...,0,0,0,0,0,0,1,0,0,0
94553,316860975,2020,48,4,0,2008,63.0,1.013,4.00,0,...,0,0,0,0,0,0,1,0,0,0

# SVD

In [94]:
# evaluate svd with logistic regression algorithm for classification
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV, train_test_split




# define dataset
X_train, X_test, y_train, y_test = train_test_split(new_df.loc[:, new_df.columns != "Incidence"], new_df["Incidence"], test_size=0.25, random_state=42)

# define the pipeline
svd = TruncatedSVD(n_components=20)
X_train_svd = svd.fit_transform(X_train)
X_test_svd = svd.transform(X_test)

c:\Users\zonca\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['bool', 'str']. An error will be raised in 1.2.
  warnings.warn(
c:\Users\zonca\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['bool', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import roc_auc_score


# Convert the training and test sets into DMatrix objects for XGBoost
dtrain = xgb.DMatrix(X_train_svd, label=y_train)
dtest = xgb.DMatrix(X_test_svd, label=y_test)

# Define the grid of hyperparameters to search
params = {
    'max_depth': [1,3],
    'learning_rate': [0.05,0.1],
    'n_estimators': [100, 200]
}

# Perform grid search with cross-validation
xgb_clf = xgb.XGBClassifier()
grid_search = GridSearchCV(xgb_clf, params, cv=5, scoring='roc_auc')
grid_search.fit(X_train_svd, y_train)

# Print the best parameters and the best AUC score
print("Best parameters: ", grid_search.best_params_)
print("Best AUC score: ", grid_search.best_score_)

# Evaluate the model on the test set
y_pred = grid_search.predict_proba(X_test_svd)[:, 1]
auc = roc_auc_score(y_test, y_pred)
print("Test set AUC: ", auc)

Best parameters:  {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
Best AUC score:  0.9999908999062577
Test set AUC:  0.9999982312264587

In [ ]:
# import pandas as pd
# import numpy as np
# from sklearn.model_selection import train_test_split
# from lightgbm import LGBMClassifier
# from sklearn.metrics import roc_auc_score
# from sklearn.model_selection import GridSearchCV, train_test_split

# # Load data
# params = {
#     'learning_rate': [0.01,0.1],
#     'n_estimators': [1000,2000],
#     'max_depth': [1,5,10]
# }

# # Train LightGBM classifier
# clf = LGBMClassifier()
# grid_search = GridSearchCV(clf, param_grid=params, cv=5)
# grid_search.fit(X_train_svd, y_train)


# # Print the best parameters and the best AUC score
# print("Best parameters: ", grid_search.best_params_)
# print("Best AUC score: ", grid_search.best_score_)

Best parameters:  {'learning_rate': 0.1, 'max_depth': 1, 'n_estimators': 2000}
Best AUC score:  0.9996504642146846

In [97]:
for column in finalsub.columns:
    finalsub[column].fillna(finalsub[column].mode()[0], inplace=True)

In [98]:
finalsub = finalsub.drop("Incidence_y", axis = 1)
finalsub

,PipeId,InspectionYear,MonthsLastRev,Severity,YearBuilt,Diameter,Length,Pressure,NumConnections,NumConnectionsUnder,...,CU,FD,FG,FI,FO,PA,PE,PN,PV,ZD
0,446859944,2019.0,23.0,4.0,2012.0,110.0,44.286,0.150,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,428124500,2019.0,24.0,4.0,2012.0,160.0,110.715,0.150,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,438428871,2019.0,23.0,4.0,2012.0,110.0,13.575,0.150,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,429034569,2019.0,23.0,4.0,2012.0,110.0,327.689,0.150,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,411184477,2019.0,23.0,4.0,2007.0,200.0,932.762,0.150,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909728,235426649,2020.0,24.0,4.0,2004.0,110.0,7.656,0.025,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909729,235426673,2020.0,24.0,4.0,2004.0,110.0,4.383,0.025,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909730,235426707,2020.0,24.0,4.0,2004.0,110.0,2.292,0.025,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909731,190956601,2020.0,24.0,4.0,2004.0,90.0,87.809,4.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
909732,228228379,2020.0,24.0,4.0,2004.0,160.0,2.325,4.000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [99]:
finalsubsvd = svd.transform(finalsub)

finalsubsvd = pd.DataFrame(finalsubsvd)

finalsubsvd

c:\Users\zonca\anaconda3\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['bool', 'str']. An error will be raised in 1.2.
  warnings.warn(

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,4.468599e+08,-2082.144697,7.863537,-31.937619,-8.434825,-3.643761,-2.460150,-1.172980,0.031433,0.043419,0.382979,-0.225111,-0.419179,0.700536,0.071999,0.002859,0.079946,0.022532,0.028341,-0.020017
1,4.281245e+08,-1872.375398,76.962369,15.323217,-9.832714,-3.631402,-3.769030,0.131975,-0.103423,0.086921,0.350233,-0.185779,-0.468749,0.692565,0.073100,0.009964,0.081669,0.014842,0.013622,-0.011103
2,4.384289e+08,-1989.575452,-23.012562,-28.989077,-8.512296,-3.555232,-2.341202,-0.732903,0.025866,0.037944,0.384924,-0.229300,-0.426643,0.698597,0.072632,-0.001206,0.077242,0.021347,0.028141,-0.016251
3,4.290346e+08,-1880.287527,290.064466,-49.270207,-7.183232,-4.063424,-3.723544,-2.405590,-0.139523,0.204299,0.285246,-0.277841,-0.382689,0.701707,0.070602,0.027940,0.109593,0.037024,0.020500,-0.048750
4,4.111845e+08,-1672.987973,899.129914,1.619752,-4.606538,-6.248197,-6.412451,-13.835733,-0.199890,0.127822,0.238993,-0.131206,-0.317314,0.725024,0.062124,0.122983,0.158864,0.064890,0.000452,-0.093673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
909728,2.354266e+08,247.311835,-34.700494,-7.160709,-1.125015,-1.679545,-2.166874,-1.076165,-0.253213,0.026099,0.347980,-0.301338,-0.447569,0.670523,0.071714,-0.016258,0.073553,0.040175,0.013240,-0.004904
909729,2.354267e+08,247.255282,-37.937344,-6.955001,-1.096971,-1.737816,-2.266854,0.964036,-0.335752,0.097411,0.326230,-0.319346,-0.466410,0.662529,0.072448,-0.024822,0.072018,0.036166,0.010643,-0.002582
909730,2.354267e+08,247.217339,-40.036844,-6.805925,-1.125485,-1.703200,-2.202461,-0.000946,-0.294109,0.061064,0.337836,-0.310164,-0.457839,0.666344,0.072121,-0.021031,0.072388,0.037928,0.011979,-0.003319
909731,1.909566e+08,739.172434,42.642676,-27.853292,-0.233648,0.508605,1.261268,-2.200850,-0.332763,0.008218,0.322814,-0.361639,-0.414198,0.683014,0.038824,0.112606,0.102986,0.071284,0.018608,-0.030128
909732,2.282284e+08,328.396062,-36.846606,43.805989,-3.336405,-0.705710,0.887411,-0.421701,-0.332936,-0.065002,0.369671,-0.234338,-0.502633,0.675369,0.040747,0.108753,0.084077,0.047476,0.009126,-0.002655

In [100]:
# Evaluate the model on the test set
results_1 = grid_search.predict(finalsubsvd)

In [101]:
results1df = pd.DataFrame(results_1)

In [102]:
results1df = pd.DataFrame(results_1)

samplesub_sub = samplesub.drop(columns = "Incidence")

finalfinal = samplesub_sub.merge(results1df, left_index = True,right_index=True)
finalfinal.rename(columns={0: "Incidence"}, inplace=True)
finalfinal

           PipeId  Incidence
0       446859944          0
1       428124500          0
2       438428871          0
3       429034569          0
4       411184477          0
...           ...        ...
909728  235426649          0
909729  235426673          0
909730  235426707          0
909731  190956601          0
909732  228228379          0

[909733 rows x 2 columns]

In [103]:
import numpy as np
finalfinal.to_csv("XGBoostplusSVD.csv", index=False)